-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Applicant CASCADE;
DROP TABLE IF EXISTS Degree CASCADE;
DROP TABLE IF EXISTS Institution CASCADE;
DROP TABLE IF EXISTS Degree_Institution CASCADE;
DROP TABLE IF EXISTS Favorite CASCADE;
DROP TABLE IF EXISTS Suggestion CASCADE;